### ISSUE TITLE
How to get GPS coordinate?

### ISSUE THREAD

**Issue by Wagi79** [ASUS-IPC/ASUS-IPC#1]
Hi,
I can see that there is specification how to get value from G-sensor and thermo sensor, but I couldn't find specs for GPS module.
Can you please help me?

Thanks

**Comment by asusiot** [comment]
hello @Wagi79 
which hardware and os are you using?

**Comment by Wagi79** [comment]
We are about to buy couple of pieces of ASUS PV100A with Yocto 2.5.

**Comment by asusiot** [comment]
hello @Wagi79 

for your reference: 
Locosys MC1612-DG
https://www.locosystech.com/en/product/dr-module-mc-1612-dg.html
