### ISSUE TITLE
How can i get the image?

### ISSUE THREAD

**Issue by Andreanbudi** [ASUS-IPC/ASUS-IPC#2]
I want to flash my pe1000n due to error because i ran out of storage, so the gui not showing
So i read the documentation, we need the bsp image for flashing, where can i download it?
I already check the asus website https://www.asus.com/networking-iot-servers/aiot-industrial-solutions/embedded-computers-edge-ai-systems/pe1000n/helpdesk_manual?model2Name=PE1000N
There's no image available
Thanks

**Comment by asusiot** [comment]
hello @Andreanbudi 
please contact the distributor or send us an email via https://www.asus.com/support/Product/ContactUs/Services/questionform/?lang=en

**Comment by Andreanbudi** [comment]
I have contacted the distrubutor but the response is very slow, I don't get the file until now. Is there another way please? It's urgent

**Comment by asusiot** [comment]
hello @Andreanbudi 
which sku of pe1000n are you using?

**Comment by Andreanbudi** [comment]
I use xavier nx
PE1000N-XT002II

**Comment by asusiot** [comment]
hello @Andreanbudi 
my colleague has sent you the file via email, please check your inbox

**Comment by Andreanbudi** [comment]
Ok thanks, I already download the file
