### ISSUE TITLE
Startup from external storage PE1000N not working

### ISSUE THREAD

**Issue by Andreanbudi** [ASUS-IPC/ASUS-IPC#3]
I want to move my system to external sd card. I already follow the wiki tutorial, but after rebooting, the option to chose the storage not showing up, instead it's instantly booting to gui like normal booting.

**Comment by asusiot** [comment]
hello @Andreanbudi 
you're right, the initrd_230707 did not replace the old initrd, hence why it didn't boot from the sdcard. we will revise the instruction. thank you and sorry for the inconvenience. 

https://github.com/ASUS-IPC/ASUS-IPC/wiki/PE1000N#31-mount-rootfs-to-external-storage

for **2. Copy initrd to the /boot path in PE1000N** please do the following: 

```
cd /boot
sudo mv initrd initrd_bak
sudo cp /media/xxx/xxx/initrd_230707 /boot/initrd
```
